
delete from pcace.I_SystemParam;
insert into pcace.I_SystemParam(id,paramClass,className,value,name,parentClass,isShow,state) values(1  ,'100','流程分类','100001','财务流程',null,null,1);
insert into pcace.I_SystemParam(id,paramClass,className,value,name,parentClass,isShow,state) values(2  ,'100','流程分类','100002','行政流程',null,null,1);
insert into pcace.I_SystemParam(id,paramClass,className,value,name,parentClass,isShow,state) values(3  ,'100','流程分类','100003','项目流程',null,null,1);
insert into pcace.I_SystemParam(id,paramClass,className,value,name,parentClass,isShow,state) values(4  ,'100','流程分类','100004','其他流程',null,null,1);
insert into pcace.I_SystemParam(id,paramClass,className,value,name,parentClass,isShow,state) values(8  ,'101','流程经手模式','101001','一人名单一人处理',null,null,1);
insert into pcace.I_SystemParam(id,paramClass,className,value,name,parentClass,isShow,state) values(9  ,'101','流程经手模式','101002','多人名单一人处理',null,null,1);
insert into pcace.I_SystemParam(id,paramClass,className,value,name,parentClass,isShow,state) values(10 ,'101','流程经手模式','101003','多人名单多人并行处理',null,null,1);
insert into pcace.I_SystemParam(id,paramClass,className,value,name,parentClass,isShow,state) values(11 ,'102','流程选人过滤规则','102001','允许选择全部指定的经办人',null,null,1);
insert into pcace.I_SystemParam(id,paramClass,className,value,name,parentClass,isShow,state) values(12 ,'102','流程选人过滤规则','102002','只允许选择本部门经办人',null,null,1);
insert into pcace.I_SystemParam(id,paramClass,className,value,name,parentClass,isShow,state) values(13 ,'102','流程选人过滤规则','102003','只允许选择上级部门经办人',null,null,1);
insert into pcace.I_SystemParam(id,paramClass,className,value,name,parentClass,isShow,state) values(14 ,'102','流程选人过滤规则','102004','只允许选择下级部门经办人',null,null,1);
insert into pcace.I_SystemParam(id,paramClass,className,value,name,parentClass,isShow,state) values(15 ,'102','流程选人过滤规则','102005','只允许选择本角色经办人',null,null,1);
insert into pcace.I_SystemParam(id,paramClass,className,value,name,parentClass,isShow,state) values(20 ,'103','流程自动选人规则','103001','不进行自动选择',null,null,1);
insert into pcace.I_SystemParam(id,paramClass,className,value,name,parentClass,isShow,state) values(21 ,'103','流程自动选人规则','103002','自动选择流程发起人',null,null,1);
insert into pcace.I_SystemParam(id,paramClass,className,value,name,parentClass,isShow,state) values(22 ,'103','流程自动选人规则','103003','自动选择本部门主管',null,null,1);
insert into pcace.I_SystemParam(id,paramClass,className,value,name,parentClass,isShow,state) values(23 ,'103','流程自动选人规则','103004','自动选择上级主管领导',null,null,1);
insert into pcace.I_SystemParam(id,paramClass,className,value,name,parentClass,isShow,state) values(24 ,'103','流程自动选人规则','103005','自动选择董事长（一级部门主管）',null,null,1);
insert into pcace.I_SystemParam(id,paramClass,className,value,name,parentClass,isShow,state) values(25 ,'103','流程自动选人规则','103006','自动选择总经理（二级部门主管）',null,null,1);
insert into pcace.I_SystemParam(id,paramClass,className,value,name,parentClass,isShow,state) values(26 ,'103','流程自动选人规则','103007','自动选择指定步骤经办人',null,null,1);
insert into pcace.I_SystemParam(id,paramClass,className,value,name,parentClass,isShow,state) values(27 ,'103','流程自动选人规则','103008','自动选择指定字段',null,null,1);
insert into pcace.I_SystemParam(id,paramClass,className,value,name,parentClass,isShow,state) values(90 ,'200','机构类型','200001','公司',null,null,1);
insert into pcace.I_SystemParam(id,paramClass,className,value,name,parentClass,isShow,state) values(100,'201','等级','201000','-',null,null,1);
insert into pcace.I_SystemParam(id,paramClass,className,value,name,parentClass,isShow,state) values(101,'201','等级','201001','一级',null,null,1);
insert into pcace.I_SystemParam(id,paramClass,className,value,name,parentClass,isShow,state) values(102,'201','等级','201002','二级',null,null,1);
insert into pcace.I_SystemParam(id,paramClass,className,value,name,parentClass,isShow,state) values(103,'201','等级','201003','三级',null,null,1);
insert into pcace.I_SystemParam(id,paramClass,className,value,name,parentClass,isShow,state) values(104,'201','等级','201004','四级',null,null,1);
insert into pcace.I_SystemParam(id,paramClass,className,value,name,parentClass,isShow,state) values(105,'201','等级','201005','五级',null,null,1);
insert into pcace.I_SystemParam(id,paramClass,className,value,name,parentClass,isShow,state) values(106,'201','等级','201006','六级',null,null,1);
insert into pcace.I_SystemParam(id,paramClass,className,value,name,parentClass,isShow,state) values(107,'201','等级','201007','七级',null,null,1);
insert into pcace.I_SystemParam(id,paramClass,className,value,name,parentClass,isShow,state) values(108,'201','等级','201008','八级',null,null,1);
insert into pcace.I_SystemParam(id,paramClass,className,value,name,parentClass,isShow,state) values(109,'201','等级','201009','九级',null,null,1);
insert into pcace.I_SystemParam(id,paramClass,className,value,name,parentClass,isShow,state) values(110,'201','等级','201010','十级',null,null,1);
insert into pcace.I_SystemParam(id,paramClass,className,value,name,parentClass,isShow,state) values(111,'202','数据类型','202001','NUMBER',null,null,1);
insert into pcace.I_SystemParam(id,paramClass,className,value,name,parentClass,isShow,state) values(112,'202','数据类型','202002','VARCHAR2',null,null,1);
insert into pcace.I_SystemParam(id,paramClass,className,value,name,parentClass,isShow,state) values(113,'202','数据类型','202003','DATE',null,null,1);
insert into pcace.I_SystemParam(id,paramClass,className,value,name,parentClass,isShow,state) values(114,'202','数据类型','202004','CHAR',null,null,1);
insert into pcace.I_SystemParam(id,paramClass,className,value,name,parentClass,isShow,state) values(115,'202','数据类型','202005','TEXT',null,null,1);
insert into pcace.I_SystemParam(id,paramClass,className,value,name,parentClass,isShow,state) values(116,'202','数据类型','202006','DATETIME',null,null,1);
insert into pcace.I_SystemParam(id,paramClass,className,value,name,parentClass,isShow,state) values(117,'202','数据类型','202007','FILE',null,null,1);
insert into pcace.I_SystemParam(id,paramClass,className,value,name,parentClass,isShow,state) values(118,'202','数据类型','202008','IMG_FILE',null,null,1);
insert into pcace.I_SystemParam(id,paramClass,className,value,name,parentClass,isShow,state) values(119,'202','数据类型','202009','IMG_LINK',null,null,1);
insert into pcace.I_SystemParam(id,paramClass,className,value,name,parentClass,isShow,state) values(120,'202','数据类型','202010','MD5加密文',null,null,1);
insert into pcace.I_SystemParam(id,paramClass,className,value,name,parentClass,isShow,state) values(121,'202','数据类型','202011','随机码UGID',null,null,1);
insert into pcace.I_SystemParam(id,paramClass,className,value,name,parentClass,isShow,state) values(122,'202','数据类型','202012','单选框',null,null,1);
insert into pcace.I_SystemParam(id,paramClass,className,value,name,parentClass,isShow,state) values(123,'202','数据类型','202013','多选框',null,null,1);
insert into pcace.I_SystemParam(id,paramClass,className,value,name,parentClass,isShow,state) values(131,'204','附件类型','204001','图片',null,null,1);
insert into pcace.I_SystemParam(id,paramClass,className,value,name,parentClass,isShow,state) values(132,'204','附件类型','204002','音频',null,null,1);
insert into pcace.I_SystemParam(id,paramClass,className,value,name,parentClass,isShow,state) values(133,'204','附件类型','204003','视频',null,null,1);
insert into pcace.I_SystemParam(id,paramClass,className,value,name,parentClass,isShow,state) values(134,'204','附件类型','204004','文本',null,null,1);
insert into pcace.I_SystemParam(id,paramClass,className,value,name,parentClass,isShow,state) values(141,'205','外文','205001','中国简体',null,null,1);
insert into pcace.I_SystemParam(id,paramClass,className,value,name,parentClass,isShow,state) values(142,'205','外文','205002','英语',null,null,1);
insert into pcace.I_SystemParam(id,paramClass,className,value,name,parentClass,isShow,state) values(143,'205','外文','205003','日语',null,null,1);
insert into pcace.I_SystemParam(id,paramClass,className,value,name,parentClass,isShow,state) values(144,'205','外文','205004','韩语',null,null,1);
insert into pcace.I_SystemParam(id,paramClass,className,value,name,parentClass,isShow,state) values(145,'205','外文','205005','法语',null,null,1);
insert into pcace.I_SystemParam(id,paramClass,className,value,name,parentClass,isShow,state) values(149,'206','分组函数','206000','groupby',null,null,1);
insert into pcace.I_SystemParam(id,paramClass,className,value,name,parentClass,isShow,state) values(150,'206','分组函数','206001','sum',null,null,1);
insert into pcace.I_SystemParam(id,paramClass,className,value,name,parentClass,isShow,state) values(151,'206','分组函数','206002','max',null,null,1);
insert into pcace.I_SystemParam(id,paramClass,className,value,name,parentClass,isShow,state) values(152,'206','分组函数','206003','min',null,null,1);
insert into pcace.I_SystemParam(id,paramClass,className,value,name,parentClass,isShow,state) values(153,'206','分组函数','206004','count',null,null,1);
insert into pcace.I_SystemParam(id,paramClass,className,value,name,parentClass,isShow,state) values(200,'801','数据状态','801000','初始',null,null,1);
insert into pcace.I_SystemParam(id,paramClass,className,value,name,parentClass,isShow,state) values(201,'801','数据状态','801001','等待校对',null,null,1);
insert into pcace.I_SystemParam(id,paramClass,className,value,name,parentClass,isShow,state) values(202,'801','数据状态','801003','等待审核入库',null,null,1);
insert into pcace.I_SystemParam(id,paramClass,className,value,name,parentClass,isShow,state) values(203,'801','数据状态','801004','已入库，等待发布',null,null,1);
insert into pcace.I_SystemParam(id,paramClass,className,value,name,parentClass,isShow,state) values(204,'801','数据状态','801005','已冻结',null,null,1);
insert into pcace.I_SystemParam(id,paramClass,className,value,name,parentClass,isShow,state) values(205,'801','数据状态','801009','已发布',null,null,1);
insert into pcace.I_SystemParam(id,paramClass,className,value,name,parentClass,isShow,state) values(301,'802','密级','802001','公开',null,1,1);
insert into pcace.I_SystemParam(id,paramClass,className,value,name,parentClass,isShow,state) values(302,'802','密级','802002','内部',null,1,1);
insert into pcace.I_SystemParam(id,paramClass,className,value,name,parentClass,isShow,state) values(303,'802','密级','802003','秘密',null,1,1);
insert into pcace.I_SystemParam(id,paramClass,className,value,name,parentClass,isShow,state) values(304,'802','密级','802004','机密',null,1,1);
insert into pcace.I_SystemParam(id,paramClass,className,value,name,parentClass,isShow,state) values(305,'802','密级','802005','绝密',null,1,1);
insert into pcace.I_SystemParam(id,paramClass,className,value,name,parentClass,isShow,state) values(306,'803','值域表','803001','数据应用字典',null,1,1);
insert into pcace.I_SystemParam(id,paramClass,className,value,name,parentClass,isShow,state) values(307,'803','值域表','803002','默认值：当前登录信息',null,1,1);
insert into pcace.I_SystemParam(id,paramClass,className,value,name,parentClass,isShow,state) values(308,'803','值域表','803003','默认值：当前日期',null,1,1);
insert into pcace.I_SystemParam(id,paramClass,className,value,name,parentClass,isShow,state) values(309,'803','值域表','803004','默认值：明日日期',null,1,1);
insert into pcace.I_SystemParam(id,paramClass,className,value,name,parentClass,isShow,state) values(314,'803','值域表','803008','默认值：自定义',null,1,1);
insert into pcace.I_SystemParam(id,paramClass,className,value,name,parentClass,isShow,state) values(315,'803','值域表','803009','业务数据',null,1,1);
insert into pcace.I_SystemParam(id,paramClass,className,value,name,parentClass,isShow,state) values(316,'803','值域表','803010','业务数据字段',null,1,1);
insert into pcace.I_SystemParam(id,paramClass,className,value,name,parentClass,isShow,state) values(317,'803','值域表','803011','加密文件',null,1,1);
insert into pcace.I_SystemParam(id,paramClass,className,value,name,parentClass,isShow,state) values(318,'803','值域表','803012','加密文件名',null,1,1);
insert into pcace.I_SystemParam(id,paramClass,className,value,name,parentClass,isShow,state) values(400,'900','系统参数：是否打印数据查询结果','900001','1',null,1,1);
insert into pcace.I_SystemParam(id,paramClass,className,value,name,parentClass,isShow,state) values(403,'902','业务参数：文件服务器web地址','902001','http://118.178.126.204/fileserver/',null,1,1); --http://118.178.126.204/fileserver/
insert into pcace.I_SystemParam(id,paramClass,className,value,name,parentClass,isShow,state) values(404,'903','业务参数：文件服务器硬盘地址','903001','E:\Tomcat\webapps\fileserver\',null,1,1); --E:\app\Tomcat\webapps\fileserver\
insert into pcace.I_SystemParam(id,paramClass,className,value,name,parentClass,isShow,state) values(405,'904','业务参数：APP_Server地址','904001','http://118.178.126.204:8099/aceserver/',null,1,1); --http://118.178.126.204:80992/aceserver/
insert into pcace.I_SystemParam(id,paramClass,className,value,name,parentClass,isShow,state) values(406,'905','业务参数：苹果开关','905001','1',null,1,1);
commit;
